default:
  model_path: "{MODEL_PATH}"
  data_path: "{PATH_TO_DATA}"
  work_dir: "{SAVE_DIRECTORY}"
  save_file: "{SAVE_FILE}"
  n_months: "{N_MONTHS_COLLECTED}"
  b_sz: "{BATCH_SIZE}"
  cuda: "{USE_GPU}"
